#Broken gdal
#FROM python:2
#2020-02-03 FROM geodata/gdal
FROM debian:buster
LABEL maintainer "Cheewai Lai <clai@csir.co.za>"

ARG SUEXEC_VER=0.2
ARG SPATIALINDEX_VER=1.8.5
ARG DOCKERIZE_VERSION=v0.6.1
ARG http_proxy
ARG https_proxy

RUN apt-get update \
 && apt-get -y install build-essential curl postgresql-client rsync python3 python3-dev python3-setuptools python3-pip python3-psycopg2 python3-shapely python3-rtree python3-gdal \
 && curl -k -fsSL -o /tmp/suexec.tgz "https://github.com/ncopa/su-exec/archive/v${SUEXEC_VER}.tar.gz" \
 && cd /tmp \
 && tar xvf suexec.tgz \
 && cd "/tmp/su-exec-${SUEXEC_VER}" \
 && make \
 && cp -af su-exec /usr/bin/ \
 && curl -k -fsSL https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xfz - -C /usr/bin \
 && pip3 install dateutils \
 && pip3 install flask \
 && pip3 install gevent \
 && pip3 install gserver \
 && pip3 install pika \
 && pip3 install psycogreen \
 && pip3 install PyYAML \
 && pip3 install rethinkdb \
 && pip3 install blinker raven --upgrade \
 && apt-get -y remove --purge build-essential python3-dev python3-setuptools \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ADD docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod 755 /docker-entrypoint.sh \
 && chown root.root /docker-entrypoint.sh
